Docker: move build & promote actions back into this repo

diff --git a/.github/workflows/docker-promote-to-environment.yml b/.github/workflows/docker-promote-to-environment.yml
--- a/.github/workflows/docker-promote-to-environment.yml
+++ b/.github/workflows/docker-promote-to-environment.yml
@@ -78,10 +78,12 @@ on:
         required: false
 
 jobs:
-  validate-and-generate-matrix:
+  validate-and-generate:
     name: Validate inputs & generate build matrix
     runs-on: ubuntu-latest
     outputs:
+      source: ${{ steps.gen-source.outputs.source }}
+      target: ${{ steps.gen-source.outputs.target }}
       variants: ${{ steps.gen-matrix.outputs.variants }}
     steps:
       - name: Validate & generate docker workflow inputs
@@ -102,22 +104,51 @@ jobs:
           # Vendor: scaleway
           scaleway-access-key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
           scaleway-secret-key: ${{ secrets.SCALEWAY_SECRET_KEY }}
+      - name: Calculate source
+        id: gen-source
+        run: |
+          target=`echo ${{ inputs.environment-target }} | tr '[:upper:]' '[:lower:]'`
+          echo "target=$target" >> "$GITHUB_OUTPUT"
+
+          if [ ! -z "${{ inputs.environment-source }}" ]; then
+            echo "source=${{ inputs.environment-source }}" >> "$GITHUB_OUTPUT"
+          else
+            env_map='${{ inputs.environment-map || env.default-tag-map }}'
+            source=`echo $env_map | jq -r ".$target"`
+
+            if [ "$source" != "null" ]; then
+              echo "source=$source" >> "$GITHUB_OUTPUT"
+            else
+              echo "Unable to calculate source for ${{ inputs.environment-target }}." >> $GITHUB_STEP_SUMMARY
+              exit 1
+            fi
+          fi
+        env:
+          default-tag-map: >  # Note that this is a JSON string
+            {
+              "development": "development",
+              "test": "development",
+              "staging": "test",
+              "production": "staging"
+            }
 
   promote-tag:
     name: Promote ${{ matrix.variant.path }} to ${{ inputs.environment-target }}
-    needs: [validate-and-generate-matrix]
-    if: ${{ needs.validate-and-generate-matrix.outputs.variants != '[]' }}
+    needs: [validate-and-generate]
+    if: ${{ needs.validate-and-generate.outputs.variants != '[]' }}
     strategy:
       matrix:
-        variant: ${{ fromJson(needs.validate-and-generate-matrix.outputs.variants) }}
+        variant: ${{ fromJson(needs.validate-and-generate.outputs.variants) }}
     runs-on: ubuntu-latest
     environment: ${{ inputs.environment-target }}
     steps:
-      - name: Prepare environment
-        id: prep-environment
-        uses: wisemen-digital/devops-github-actions/.github/actions/docker/prep-environment@main
+      # Setup
+      - name: Setup Docker environment
+        id: setup
+        uses: wisemen-digital/devops-github-actions/.github/actions/docker/setup@main
         with:
           vendor: ${{ inputs.vendor }}
+          container-registry: ${{ vars.CONTAINER_REGISTRY_ENDPOINT }}
           image: ${{ inputs.image }}
           k8s-labels: ${{ vars.K8S_LABELS }}
           variant-path: ${{ matrix.variant.path }}
@@ -129,23 +160,22 @@ jobs:
           digitalocean-token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
           # Vendor: scaleway
           scaleway-secret-key: ${{ secrets.SCALEWAY_SECRET_KEY }}
+      # Re-tag
       - name: Re-tag image
-        uses: wisemen-digital/devops-ga-docker-promote-tag@main
-        with:
-          container-registry: ${{ vars.CONTAINER_REGISTRY_ENDPOINT }}
-          container-registry-username: ${{ steps.prep-environment.outputs.registry-username }}
-          container-registry-password: ${{ steps.prep-environment.outputs.registry-password }}
-          image: ${{ steps.prep-environment.outputs.image }}${{ steps.prep-environment.outputs.image-suffix }}
-          source-tag: ${{ inputs.environment-source }}
-          target-tag: ${{ inputs.environment-target }}
-          tag-map: ${{ inputs.environment-map }}
+        shell: bash
+        run: docker buildx imagetools create "${image_ref}:${source_tag}" --tag "${image_ref}:${target_tag}"
+        env:
+          image_ref: ${{ steps.setup.outputs.registry }}/${{ steps.setup.outputs.image }}
+          source_tag: ${{ needs.validate-and-generate.outputs.source }}
+          target_tag: ${{ needs.validate-and-generate.outputs.target }}
+      # Rollout
       - name: Rollout on cluster
         uses: wisemen-digital/devops-github-actions/.github/actions/infra/k8s/rollout@main
         with:
           vendor: ${{ inputs.vendor }}
           cluster-id: ${{ vars.K8S_CLUSTER_ID }}
           rollout-deployments: ${{ vars.K8S_DEPLOYMENTS }}
-          rollout-labels: ${{ steps.prep-environment.outputs.rollout-labels }}
+          rollout-labels: ${{ steps.setup.outputs.k8s-labels }}
           rollout-namespace: ${{ vars.K8S_NAMESPACE }}
           # Vendor: azure
           azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
